### ISSUE TITLE
D2 Use the SQLite text search instead of a separate Whoosh search index

### ISSUE THREAD

**Issue by cmutel** [brightway-lca/brightway2-data#103]
* [FTS5](https://www.sqlite.org/fts5.html)
* [Tutorial](https://www.sqlitetutorial.net/sqlite-full-text-search/)

**Comment by michaelweinold** [comment]
I added a testing notebook here: [`dev/fts5_bw_dev.ipynb`](https://github.com/brightway-lca/brightway2-data/blob/switch_to_fts5/dev/fts5_bw_dev.ipynb).

While I can't test _this notebook_ in WASM (ie. Brightway Live) due to https://github.com/brightway-lca/brightway2-data/issues/172, I was able to confirm that SQL native text search works fine in WASM: [`dev/fts5_wasm_dev.ipynb`](https://github.com/brightway-lca/brightway2-data/blob/switch_to_fts5/dev/fts5_wasm_dev.ipynb) 🎉

**Comment by michaelweinold** [comment]
#TODO 

 - [ ] weights on search queries
